version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dizzy
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./api/sql:/docker-entrypoint-initdb.d
  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dizzy
      JWT_SECRET: devsecret
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
