name: CI

on:
  push:
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dizzy
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r api/requirements.txt
      - name: Init DB schema
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d dizzy -f api/sql/001_init.sql
      - name: Run API tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dizzy
          JWT_SECRET: devsecret
          API_BASE: http://localhost:8000
        run: |
          uvicorn api.app:app --host 0.0.0.0 --port 8000 &
          sleep 2
          pytest -q api/tests

